version: '3.1'
services:
  odoo:
    container_name: odoo
    build:
      context: ./dockerfile
      dockerfile: odoo.Dockerfile
    volumes:
      - ./addons-extra:/mnt/addons-extra
      - ./odoo-config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069
    depends_on:
      - database
    #command: odoo -d db_name -u modul_ename
    restart: always
  
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - database-data:/var/lib/postgresql/data/pgdata
    #ports:
    #  - 5432:5432
    #command: -p 5433
    environment:
      - POSTGRES_PASSWORD=${postgres_pw}
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    links:
      - "database:pgsql-server"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgAdmin_email}
      PGADMIN_DEFAULT_PASSWORD: ${pgAdmin_pw}
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - database
    restart: unless-stopped
    
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/html
    ports:
      - 80:80   #non secure
      - 443:443 #ssl
    depends_on:
      - odoo
    restart: unless-stopped

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/html -- email ${certbot_email} --agree-tos --no-eff-email -d ${certbot_domain} -d www.${certbot_domain}
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/html

  vscode:
    image: codercom/code-server
    volumes:
      - .:/home/coder/project
    ports:
      - "8080:8080"
    environment:
      - USER=${USER}
      - PASSWORD=${vsc_password}

volumes:
  odoo-web-data:
  database-data:
  pgadmin-data: